jakzal/phpqa

tools.json
Small bit of maintenance. I've gone through the packages that use Github releases and checked they are up to date with the latest release. PhpMetrics was the only tool that needed updating.
| Tool | Old Version | New Version |
| - | - | - |
| PhpMetrics | v2.3.0 | v2.3.2 |
=> Updated PhpMetrics to v2.3.2

Dockerfile, Dockerfile-alpine
This removes the deprecated `MAINTAINER` instruction from the Dockerfile (see [here](https://docs.docker.com/engine/deprecated/#maintainer-in-dockerfile)) and uses `COPY` in favour of `ADD` as per [best practices](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#add-or-copy) for writing Dockerfiles.
=> Dockerfile maintenance

tools.json, tools.php
The latest tag will now be used with box and composer installations if it's available.
Since not all tagged version actually build cleanly (i.e. php-formatter), I also added a way to force the version to install in both installation methods:
```json
"box-build": {
"repository": "https://github.com/mmoreram/php-formatter.git",
"phar": "build/php-formatter.phar",
"bin": "/usr/local/bin/php-formatter",
"version": "1fa3d9a3e1c67654f3fe2511bd28fa7c33b59d7e"
},
"composer-install": {
"repository": "https://github.com/Symplify/EasyCodingStandard.git",
"version": "v2.5.12"
}
```
=> Install tagged versions with box and composer install (if available)

CONTRIBUTING.md, Dockerfile, Dockerfile-alpine, README.md, tools.json, tools.php
Fixes #56 
Phpstan extensions can now be installed with the bin plugin in the `phpstan` namespace:
```
composer global bin phpstan require phpstan/phpstan-phpunit
```
I also switched all `composer global install`s to the composer bin plugin as that doesn't make any difference in the image size.
=> Use composer-bin-plugin with phpstan and other packages installed globally

README.md
Single quotes are evaluated dynamically whilst double quotes are evaluated at time of creation and, thereafter, PWD never changes.
Tested on macOS adding alias to .zshrc
Tested on Ubuntu adding alias to .bashrc
On both cases only single quotes produce the desired outcome.
=> Wrap alias in single quotes instead of double quotes

README.md
Hello,
Thank you for creating this docker image, it's really convenient to have all these tools in a single image.
Today I was using it to run a bunch of tools on my code and at some point one of them took too much time to run. So I tried to cancel it, using a Control-C as usual but of course, it's not working the same way when running in a container.
>  docker run -it --rm -v $PWD:/project -v $PWD/tmp-phpqa:/tmp -w /project jakzal/phpqa deprecation-detector                                                                                               
> Checking your application for deprecations - this could take a while ...                                                                                                               
> …
=> Add a mention to docker run --init option in the README

Makefile
The most recently nightly tag wasn't pushed as the build tag was overwritten.
=> Do not parametrise nightly builds

tools.json
CoverageChecker allows QA tools to run on a single pull request.
This allows running these tools on a large legacy code base without having to fix all of the outstanding issues. Only the code you change needs to conform to the standard selected
Eg PSR-2 check only on changed code, or ensure every pull request has a test covering the new code
Edit:
Sorry opened a new PR the last commit didnt seem to come though - this is the same branch but it works fine now ?
=> add CoverageChecker

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
PHPCS set parallel to 1 if `pcntl` php extension is not installed. see https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Runner.php#L379
=> add pcntl for phpcs parallel feature

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
New tools:
* roave-backward-compatibility-check - [Tool to compare two revisions of a class API to check for BC breaks](https://github.com/Roave/BackwardCompatibilityCheck)
Updates:
* phan (1.2.4 -> 1.2.5)
* psalm (3.0.17 -> 3.1.0)
=> Toolbox update

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Updates:
* Install phpda with composer-bin-plugin https://github.com/jakzal/toolbox/pull/81
* Install tools requiring a legacy nikic/php-parser in their own namespace https://github.com/jakzal/toolbox/pull/81
* Move php-coupling-detector and php-assumptions back to the tools namespace https://github.com/jakzal/toolbox/pull/81
=> Update toolbox 1.4.4 -> 1.4.5

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Updates:
* phan (1.2.8 -> 1.3.1) https://github.com/jakzal/toolbox/pull/84 https://github.com/jakzal/toolbox/pull/85
* psalm (3.2.7 -> 3.2.9) https://github.com/jakzal/toolbox/pull/85
Changes:
* phpda was moved to the tools scope as it now supports the latest php-parser. It's now only available on PHP 7.3 https://github.com/jakzal/toolbox/pull/87
=> Update toolbox 1.4.6 -> 1.5.0

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Previous release included phars with development dependencies.
=> Update toolbox 1.5.0 -> 1.5.2

README.md
Small change in readme.MD. 
When using e.g. `$(pwd)` arguments should be always encapsulated with double quotes.
If not, command would fail if directory in path have e.g. whitespace.
=> Encapsulation of arguments in readme file

7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Fixes #183 
pcov is disabled by default so it doesn't affect performance when it's not needed,
and doesn't break interoperability with other coverage extensions.
It can be enabled by setting `pcov.enabled=1`:
```
phpqa php -d pcov.enabled=1 ./vendor/bin/phpunit --coverage-text
```
```
phpqa /tools/infection run --initial-tests-php-options='-dpcov.enabled=1'
```
=> Include pcov

.github/workflows/nightly-builds.yml, .travis.yml, Makefile
=> Run nightly builds on github

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Latest version of Rector complains about missing `intl` extension. I would consider it reasonable to add this to the PHP builds.
`Notice: RectorPrefix20210124\Nette\Utils\Strings::toAscii(): it is recommended to enable PHP extensions 'intl'. in /tools/.composer/vendor-bin/rector/vendor/rector/rector-prefixed/vendor/nette/utils/src/Utils/Strings.php on line 124`
=> Add intl extension

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
**Breaking changes**:
* Install larastan in a separate namespace with its own phpstan installation. Phpstan installation with larastan is available as . https://github.com/jakzal/toolbox/pull/349
Updates:
* psalm (4.6.0 -> 4.6.1) https://github.com/jakzal/toolbox/pull/351
New tools:
* phpcs-security-audit - [Finds vulnerabilities and weaknesses related to security in PHP code](https://github.com/FloeDesignTechnologies/phpcs-security-audit) https://github.com/jakzal/toolbox/pull/345 (thank you @mihai-stancu)
* phpcodesniffer-composer-install - [Easy installation of PHP_CodeSniffer coding standards (rulesets).](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) https://github.com/jakzal/toolbox/pull/345 …
=> Update toolbox 1.40.1 -> 1.41.0

7.3/alpine/Dockerfile, 7.4/alpine/Dockerfile, 8.0/alpine/Dockerfile, Dockerfile-alpine
Images generated with alpine graphviz (with `deptrac`) have squares instead of characters. Installing `ttf-freefont` fixes it
Before:
After
=> Add fonts required for graphviz on alpine

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
* Lock phpstan for larastan until larastan updates its composer.json https://github.com/jakzal/toolbox/commit/24316ada6a4c8a8fb11504d9bd6f4083ae2334e5
Updates:
* infection (0.21.0 -> 0.21.4) https://github.com/jakzal/toolbox/pull/365 https://github.com/jakzal/toolbox/pull/366 https://github.com/jakzal/toolbox/pull/368 https://github.com/jakzal/toolbox/pull/371
* psalm (4.6.1 -> 4.6.4) https://github.com/jakzal/toolbox/pull/366 https://github.com/jakzal/toolbox/pull/381
* box (3.8.5 -> 3.11.1) https://github.com/jakzal/toolbox/pull/358 (thanks @Pen-y-Fan)
* yaml-lint (1.1.3 -> 1.1.4) https://github.com/jakzal/toolbox/pull/372
* deptrac (0.11.1 -> 0.12.0) https://github.com/jakzal/toolbox/pull/373
Additions:
* …
=> Update toolbox 1.42.0 -> 1.43.1

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
I'm adding [`phive`](https://phar.io) to `phpqa` via jakzal/toolbox#369.
In support of that `phpqa` needs to have GPG available at runtime.
=> Preparing to add phive requires GPG support at runtime.

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Rebuild the phar with latest box, scoper, and Symfony polyfills whitelisted.
=> Update toolbox 1.45.0 -> 1.45.4

.github/workflows/build.yml
Otherwise, docker [doesn't load the image properly](https://github.com/jakzal/phpqa/runs/2591021423?check_suite_focus=true#step:10:239). The loaded image is **occasionally** missing the entrypoint:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/entrypoint.sh": stat /entrypoint.sh: no such file or directory: unknown.
Error: Process completed with exit code 1.
```
=> Separate platform builds

README.md, docs/cookbook/README.md, docs/cookbook/ampq.md, docs/cookbook/xdebug.md
hi @jakzal 
as discussed in #344 here are the first recipes  for the PHPQA Cookbook...  
it includes:
- cookbook for AMPQ extension
- cookbook for Xdebug
- index of the cookbook
- reference in the base README to the cookbook
dGo
=> doc/cookbook with two first recipes 

.github/workflows/build.yml, Makefile, alpine/Dockerfile, debian/Dockerfile
This adds a build secret in the Dockerfile that can be provided and will mount over the `.composer/auth.json` in the container while the `toolbox install` command is running.
This will hopefully mean composer is always authenticated and won't be rate-limited. Suggestions about how to tell from composer's output whether it's authed would be welcome.
I'm not sure how to do the same for Phive. They only support a token as environment variable, which would leave the secret in the image (see https://github.com/phar-io/phive/issues/372).
=> Authenticate with Composer to avoid rate limiting

Dockerfile
=> feat: enable Opcache in CLI

Makefile
=> Update the list of tools according the latest release

Dockerfile
It is now loaded by default upstream: https://github.com/docker-library/php/pull/1587
Fixes #455
=> Do not load opcache explicitly

Dockerfile
We used `jakzal/phpqa` on GitHub Actions:
https://github.com/liip/LiipTestFixturesBundle/blob/16da6812375dc84e537f1ba73cb88a7108ba256e/.github/workflows/qa.yml?plain=1#L29-L36
`composer install` was called automatically because of this line:
https://github.com/jakzal/phpqa/blob/7c5e94df1e3bbb97c8c26b4e08066f1b1b54b742/Dockerfile#L209
It added 270 lines to the job log because `composer install` show every downloaded then installed package.
I had to play with the env vars to hide the output of Composer while keeping the output of PHPStan:
- https://github.com/liip/LiipTestFixturesBundle/pull/360/files (changes)
- https://github.com/liip/LiipTestFixturesBundle/pull/360 (PR)
With this PR, the output of `composer install` will be disabled, so that we will only see the output of the tool.
If …
=> feat: hide output of automatic call to `composer install`
