jakzal/phpqa

README.md
=> Suggest creating an alias

tools.json
I have updated several tools to their next minor version:
| Tool | Old New Version | Old Version |
| - | - | - |
| phan | 0.10.0 | 0.9.4 |
| PhpMetrics | 2.3.0 | 2.2.0 |
| phpstan | 0.8.5 | 0.8.3 |
=> Updating several tools

README.md
=> Document php-dbg availability

Dockerfile, Dockerfile-alpine, install-composer.sh, tools.php
Latest development version of composer seems to have broken installing development versions (`composer install foo/bar:dev-master`).
=> Install a stable version of composer the recommended way

tools.json
* Update phan 0.10.1 -> 0.11.0
=> Update phan & phpstan

Dockerfile, Dockerfile-alpine
It's not gonna work just yet, until [composer is fixed](https://github.com/composer/composer/issues/6859).
=> Switch to PHP 7.2

tools.php
https://github.com/composer/composer/issues/6859 is fixed now
=> Install global composer packages in one go again

README.md, tools.json
Once https://github.com/mmoreram/php-formatter/pull/36 is merged this should build again.
=> Bring the php-formatter back

README.md, tools.json
=> Add infection, an AST based PHP Mutation Testing Framework

.travis.yml, tools.php
For now it's meant to be used locally, but travis will also mention at the end of the build if the tools.json needs updating. In future, would be nice if travis sent a PR ;)
=> Add a command to automatically update phar versions

README.md
=> Add some docker hub badges

.travis.yml
=> Trigger a build on docker hub during the daily travis build

README.md, tools.json
Project repo: https://github.com/overtrue/phplint
=> Add overtrue/phplint, a parallel php linter

.travis.yml, tools.json
* Update phan 0.12.7 - 0.12.8
* Update psal to 2.0.0 and switch to phar installation
=> Fix the build

Dockerfile, Dockerfile-alpine, tools.json
=> Switch phpcf to phar installation

tools.json
=> Use stable version of php-assumptions

tools.json
=> Psalm & phan & infection update

README.md, tools.json
https://github.com/psecio/parse
=> Add psecio-parse, a static security scanner

tools.json
A small change to update a couple of tools to their latest releases.
| Tool | Current Version | New Version |
|---|---|---|
| Phan | 0.12.12 | 0.12.13 |
| Psalm | 2.0.2 | 2.0.4 |
=> Updating Phan and Psalm to latest releases

tools.json
=> Update psalm (2.0.4 -> 2.0.5)

tools.json
=> Update phpspec and infection

Dockerfile, Dockerfile-alpine, README.md, tools.php
=> Move composer dir and cloned tools outside of the /root directory

Dockerfile, Dockerfile-alpine
=> Update composer to 1.7

tools.json
=> Update infection (0.9.0 -> 0.10.0-beta.4)

7.1/alpine/tools.json, 7.2/alpine/tools.json, tools.json
=> Upgrade: Psalm 2.0.9 -> 2.0.10

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.1/debian/tools.json, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.2/debian/tools.json, Dockerfile-alpine, Dockerfile-debian
=> Make unzip available in the final image

tools.json
Let's update some phars before I get time to finish the toolbox.
=> Bump versions of inspection, phan, phpspec, psalm

7.1/alpine/tools.json, 7.1/debian/tools.json, 7.2/alpine/tools.json, 7.2/debian/tools.json, 7.3/alpine/tools.json, 7.3/debian/tools.json, README.md, tools.json
* infection 0.10.5 -> 0.11.4
* phan 1.1.2 -> 1.1.8
* psalm 2.0.15 -> 3.0.5
=> Update infection, psalm and phan

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
=> Update toolbox to 1.2.1 and prepare for the release

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Always install the latest version of toolbox

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Lock toolbox version again to prevent github api timeouts

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Update toolbox to 1.2.5

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Tool updates:
* psalm (3.0.15 -> 2.0.17)
* phan (1.2.3 -> 1.2.4)
=> Update toolbox to 1.2.6

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Keep make in the final image

README.md
=> Reference PHP package starter-kit

.travis.yml
=> Only trigger docker hub builds once

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.org/jakzal/phpqa/builds/507979111).
New tools:
* rector - [Tool for instant code upgrades and refactoring](https://github.com/rectorphp/rector) #61 
* paratest - [Parallel testing for PHPUnit](https://github.com/paratestphp/paratest) #62 
* phpstan-localheinz-rules - [Additional rules for PHPstan](https://github.com/localheinz/phpstan-rules) #63 
* composer-normalize - [Composer plugin to normalize composer.json files](https://github.com/localheinz/composer-normalize) #64 
Updates:
* psalm (3.1.0 -> 3.1.1) #59
=> Update toolbox 1.3.0 -> 1.4.0

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.org/jakzal/phpqa/builds/508060985).
Updates:
* psalm (3.1.1 -> 3.2.2)
* deptrac (0.4.0 -> 0.5.0)
* phan (1.2.5 -> 1.2.6)
=> Update toolbox 1.4.0 -> 1.4.1

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Bug fixes:
* Manually link to composer-bin-plugin installed commands to guarantee the correct version of a tool is used https://github.com/jakzal/toolbox/issues/73 
Updates:
* phan (1.2.6 -> 1.2.7)
=> Update toolbox 1.4.1 -> 1.4.2

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Bugfixes:
* use github releases for dephpend as their website is down https://github.com/jakzal/toolbox/pull/76
Updates:
* psalm (3.2.2 -> 3.2.4) https://github.com/jakzal/toolbox/pull/75
=> Update toolbox 1.4.2 -> 1.4.3

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.com/jakzal/phpqa/builds/107696483).
Updates:
* phan (1.2.7 -> 1.2.8) https://github.com/jakzal/toolbox/pull/78
* psalm (3.2.4 -> 3.2.5) https://github.com/jakzal/toolbox/pull/79
=> Update toolbox 1.4.3 -> 1.4.4

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.com/jakzal/phpqa/builds/108418431).
Updates:
* dephpend (0.5.0 -> 0.6.0) https://github.com/jakzal/toolbox/pull/82
* psalm (3.2.5 -> 3.2.7) https://github.com/jakzal/toolbox/pull/82
=> Update toolbox 1.4.5 -> 1.4.6

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Updates:
* phan (1.3.2 -> 1.3.4) https://github.com/jakzal/toolbox/pull/93 https://github.com/jakzal/toolbox/pull/97
* psalm (3.2.10 -> 3.2.12) https://github.com/jakzal/toolbox/pull/93 https://github.com/jakzal/toolbox/pull/96
=> Update toolbox 1.5.2 -> 1.5.3

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.com/jakzal/phpqa/builds/112830244).
Updates:
* phan (1.3.4 -> 2.0.0) https://github.com/jakzal/toolbox/pull/100
* psalm (3.2.12 -> 3.3.0) https://github.com/jakzal/toolbox/pull/100
=> Update toolbox 1.5.3 -> 1.5.4

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Updates:
* infection (0.12.2 -> 0.13.1) https://github.com/jakzal/toolbox/pull/106
* psalm (3.3.0 -> 3.3.2) https://github.com/jakzal/toolbox/pull/106
=> Update toolbox 1.5.4 -> 1.5.5

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
:robot: This pull request was automagically sent from [Travis CI](https://travis-ci.com/jakzal/phpqa/builds/113799582).
New tools:
* phpinsights - [Analyses code quality, style, architecture and complexity](https://phpinsights.com/) https://github.com/jakzal/toolbox/pull/104 (thanks @Pierstoval)
=> Update toolbox 1.5.5 -> 1.6.0

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Composer cache wasn't properly removed.
=> Lower size of the image

README.md
same as #122 for apps  :grin: 
(preview at https://github.com/jakzal/phpqa/blob/c95e6f701941ef577b514b1cf1a2d948804905fe/README.md#starter-kits--templates)
=> Add symfony application starter kit reference

7.1/alpine/Dockerfile, 7.1/debian/Dockerfile, 7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Update composer to 1.9

7.2/alpine/Dockerfile, 7.2/alpine/entrypoint.sh, 7.2/debian/Dockerfile, 7.2/debian/entrypoint.sh, 7.3/alpine/Dockerfile, 7.3/alpine/entrypoint.sh, 7.3/debian/Dockerfile, 7.3/debian/entrypoint.sh, Dockerfile-alpine, Dockerfile-debian, Makefile, README.md, entrypoint.sh
=> Install composer dependencies if run as a github action

7.2/alpine/entrypoint.sh, 7.2/debian/entrypoint.sh, 7.3/alpine/entrypoint.sh, 7.3/debian/entrypoint.sh, entrypoint.sh
=> Fix the entrypoint on debian

entrypoint.sh
=> Support bitbucket pipelines

.github/workflows/update-toolbox.yml, .travis.yml, Makefile
=> Run toolbox updates on github

.github/workflows/daily-builds.yml, .travis.yml
=> Run daily builds on github

7.2/alpine/Dockerfile, 7.2/debian/Dockerfile, 7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Switch to composer 2

Makefile
=> Stop updating PHP 7.2 images

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Also added the docker-php-ext-configure statement which appears to be necessary
=> Add intl extension

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Updates:
* infection (0.20.2 -> 0.21.0) https://github.com/jakzal/toolbox/pull/335
* phan (4.0.2 -> 4.0.3) https://github.com/jakzal/toolbox/pull/336
=> Update toolbox 1.39.0 -> 1.39.1

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Updates:
* twigcs (4.0.0 -> 5.0.0) https://github.com/jakzal/toolbox/pull/340
* churn (1.3.0 -> 1.4.0) https://github.com/jakzal/toolbox/pull/341
* deptrac (0.10.2 -> 0.11.1) https://github.com/jakzal/toolbox/pull/342 https://github.com/jakzal/toolbox/pull/337 (thanks @smoench)
* psalm (4.4.1 -> 4.5.1) https://github.com/jakzal/toolbox/pull/343 https://github.com/jakzal/toolbox/pull/344
Changes:
*  was moved from  to  https://github.com/jakzal/toolbox/pull/337 (thanks @smoench)
=> Update toolbox 1.39.1 -> 1.40.0

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Updates:
* psalm (4.5.1 -> 4.6.0) https://github.com/jakzal/toolbox/pull/346 https://github.com/jakzal/toolbox/pull/347
=> Update toolbox 1.40.0 -> 1.40.1

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian, README.md
Updates:
* churn (1.4.0 -> 1.5.0)  https://github.com/jakzal/toolbox/pull/352
* Enable ecs on PHP 8 https://github.com/jakzal/toolbox/pull/355
* Available list converted to table with matrix https://github.com/jakzal/toolbox/pull/356 (thank you @Pen-y-Fan)
=> Update toolbox 1.41.0 -> 1.42.0

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
Additions:
* psalm-plugin-phpunit - [Psalm plugin for PHPUnit](https://github.com/psalm/psalm-plugin-phpunit) https://github.com/jakzal/toolbox/pull/252 thanks @dkarlovi 
* psalm-plugin-symfony - [Psalm Plugin for Symfony](https://github.com/psalm/psalm-plugin-symfony) https://github.com/jakzal/toolbox/pull/252  thanks @dkarlovi
=> Update toolbox 1.43.1 -> 1.44.0

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
* Update the phive signature for phpbench https://github.com/jakzal/toolbox/commit/4da356378a77547acf2e3d95c8c98badf4a5420b
=> Update toolbox 1.45.0 -> 1.45.1

7.3/alpine/Dockerfile, 7.3/debian/Dockerfile, 7.4/alpine/Dockerfile, 7.4/debian/Dockerfile, 8.0/alpine/Dockerfile, 8.0/debian/Dockerfile, Dockerfile-alpine, Dockerfile-debian
=> Update toolbox 1.45.1 -> 1.45.2

.github/workflows/build.yml
Build for both amd64 and arm64 (Apple M1).
=> Build multi-arch images

alpine/Dockerfile, debian/Dockerfile
Closes #350.
Built both Alpine and Debian images successfully.
=> feat: add ssh utility (for Git)

.github/workflows/build.yml
re https://github.com/docker/build-push-action/issues/252
=> Replace local cache with gha since it is now supported

.github/workflows/build.yml
Previous attempts: https://github.com/jakzal/phpqa/pull/303 https://github.com/jakzal/phpqa/pull/306 https://github.com/jakzal/phpqa/pull/318 were reverted in https://github.com/jakzal/phpqa/commit/8034af81a5a435c9d921a51d74bdffe6ebe3b583.
=> Build arm64 images

.github/workflows/build.yml
Adds the ARM images to the verify step in CI
=> Verify all platforms

Dockerfile
=> fix: make Composer's config.json readable by any user

.github/workflows/release.yml, Makefile
=> Automagically make a new release if the daily build has succeeded
